#ifndef _MEMPOOL_MEMPOOL_CONFIG_H_
#define _MEMPOOL_MEMPOOL_CONFIG_H_

#define MP_ENABLED 0
#define MP_VERBOSE 0
#define MP_OVERLOAD_STD 0

#define MP_STATIC_POOL 0

#define MP_ARENA_SIZE (1024 * 1024 * 10)
#define MP_ALLOW_GROW_ARENA 1
#define MP_GROW_FACTOR 2

#define MP_ALLOW_REUSE 0

#endif
